---
language: objective-c

sudo: true

before_install:
  # Setup Python environment
  - source tests/terryfy/travis_tools.sh
  - export CC=clang
  - export CXX=clang++
  - get_python_environment macpython 2.7.10 venv

install:
  # Create Workspace directory
  - mkdir -p ~/Workspace/
  - sudo -s cp -r ../dotfiles ~/Workspace/dotfiles

script:
  # Execute the bootstrapping script
  - cd ~/Workspace/dotfiles
  - sudo -s ./bootstrap.sh --force --no-update
  # Execute the update script
  - cd ~/.ansible
  - export PATH=/opt/homebrew/bin:$PATH
  - sudo -s ansible-playbook -i hosts -e "node_upgrade_all=false" site.yml
