---
- name: Update Homebrew and its managed packages.
  homebrew:
    update_homebrew: yes
    upgrade_all: yes

- name: Get list of configured Homebrew packages.
  command: cat {{ dotfiles_local }}/brew_packages
  register: packages
  always_run: yes
  changed_when: False

- name: Ensure configured Homebrew packages are installed.
  homebrew:
    name: "{{ item }}"
    state: present
  with_items: packages.stdout_lines
